#==========================================
# Project configs
#==========================================
project:

  # To change in your project!
  repositoryUrl: https://github.com/FrancisRoc/nhl-pool-api

  # To change in your project!
  # Leave empty if no such discussion URL exists
  discussionUrl: TODO

  # To change in your project!
  maintainers:
    - name: Francis Rochon
      email: francis.rochon99@gmail.com

#==========================================
# Logging configs
#==========================================
logging:
  # If the path starts with a ".", it is considered to be relative
  # to the root of the project.
  dir: ./log
  level: info
  humanReadableInConsole: false
  addStackTraceToErrorMessagesInDev: false
  logSource: false
  logRotateFilesNbr: 30
  logRotateThresholdMB: 100
  logRotateMaxTotalSizeMB: 1000

#==========================================
# Server configs
#==========================================
server:
  port: 12345
  swaggerEditorAlonePort: 12346

#==========================================
# Debug configs
#==========================================
debug:
  host: 0.0.0.0
  port: 5858

#==========================================
# API configs
# *Public* informations to access the API.
#==========================================
api:
  scheme: https
  host: localhost
  port: 12345
  endpointTypeRoots:
    api: /api
    documentation: /documentation
    diagnostics: /diagnostics
  domainPath: /nhl/poolApp

#==========================================
# Routing configs
#==========================================
routing:
  caseSensitive: false
  maxRequestSizeMb: 50
  routes:
    # Those routes will be prefixed with "/documentation" + the domainPath
    openAPI:
      specsFile: /v1/specification
      ui: /v1/ui
      editor: /v1/editor
    readme:
      route: /v1/readme
    # Those routes will be prefixed with "/diagnostics" + the domainPath
    diagnostics:
      ping: /v1/ping
      info: /v1/info

#==========================================
# Templating Engine
#==========================================
templatingEngine:
  enableCache: true

#==========================================
# Open API configs
#==========================================
openApi:
  # Note that "true" won't work on the "production"
  # environment...
  exposeSwaggerEditor: false

#==========================================
# Data Sources configs
#==========================================
dataSources:
  mongodb:
    connectString: mongodb://localhost:27017/nhlPoolApp
    secret: "4wEea?/w>4{3+Ye6"

#==========================================
# Acces nhl API
#==========================================
nhlApi:
  nbPlayersLimit: 350
  responseEncoding: utf8
  httpOptions:
    host: www.mysportsfeeds.com
    port: 443
    method: GET
