logging:
  level: debug
  humanReadableInConsole: true
  addStackTraceToErrorMessagesInDev: true
  logSource: true

api:
  scheme: https
  host: nhlpoolhelperapi.herokuapp.com
  port: 443
  domainPath: /nhl/poolApp

openApi:
  exposeSwaggerEditor: true

templatingEngine:
  enableCache: false


