logging:
  level: debug
  humanReadableInConsole: true
  addStackTraceToErrorMessagesInDev: true
  logSource: true

api:
  scheme: https
  host: localhost
  port: 12345
  endpointTypeRoots:
    api: /api
    documentation: /documentation
    diagnostics: /diagnostics
  domainPath: /nhl/poolApp

openApi:
  exposeSwaggerEditor: true

dataSources:
  mongodb:
    connectString: mongodb://localhost:27017/nhlPoolApp

templatingEngine:
  enableCache: false


