logging:
  level: debug
  humanReadableInConsole: true
  addStackTraceToErrorMessagesInDev: true
  logSource: true

api:
  scheme: http
  host: https://nhlpoolhelperfrank.herokuapp.com
  port: 8080
  domainPath: /nhl/poolApp

openApi:
  exposeSwaggerEditor: true

templatingEngine:
  enableCache: false


